@startuml class

class Пациент {
- Номер карточки
- ФИО пациента
- Год рождения
- Адрес
- Пол
+ Зарегистрировать()
+ Обновить()
+ Удалить()
}

enum "Вид лечения" {
- стационарно
- амбулаторно
}

class Лечение {
- ФИО пациента
- Описания лечения
- Вид лечения
+ Назначить()
+ Переопределить()
}

class Рецепты {
- Номер рецепта
- ФИО врача
- Название лекарства
- Количество
- Периодичность
+ Выписать()
}

class 

@enduml