@startuml activity
title Интегрировать аккаунт GitHub
|U| Пользователь
|S| Система авторизации
|G| GitHub

|U|
start
:Нажимает кнопку \n"Связать с GitHub";

|S|
if (Аккаунт GitHub уже связан?) then (Да)
  :Отобразить сообщение, \nчто аккаунт уже связан;
  stop
else (Нет)
  :Перенаправить на страницу \nавторизации GitHub;
endif

|U|
:Авторизуется (OAuth);

|G|
:Перенаправляет обратно \nв Task Manager Pro \nс кодом авторизации;

|S|
:Получает код авторизации GitHub;
:Отправляет запрос на получение access token;

|G|
if (Данные запроса соответствуют?) then (Да)
  :Отправить access token;
else (Нет)
  :Отправить сообщение \nоб ошибке;
endif

|S|
if (Обмен прошел успешно?) then (Да)
  :Сохранить access token \nв базе данных;
  :Отобразить сообщение \nоб успешной интеграции с GitHub;
else (Нет)
  :Отобразить сообщение \nоб ошибке интеграции;
endif
stop
@enduml