@startuml
title Диаграмма состояний для класса "Пациент"
skinparam state {
  BackgroundColor #7acff5
}

[*] --> Незарегистрированный
Незарегистрированный -> Зарегистрированный: оформить карточку
[*] --> Зарегистрированный
state "Записан на прием" as s1
Зарегистрированный --> s1:выписать талон на прием
s1: entry / Сверить данные талона
state "На приеме" as s2
s2:entry / Анамнез
s2:do / Поставить диагноз
s2:exit / Назначить лечение
s1 --> s2
Лечение <- s2
Лечение -> s1
Вылечен <- Лечение
Вылечен --> [*]




@enduml