@startuml activity
title Диаграмма деятельностей сотрудника регистратуры 
start
if (Зарегистрирован ли пациент?) then ([нет])
fork
:Получить
паспорт;
fork again
:Получить
страховой полис;
end fork
:Открыть новую карточку;
:Ввести данные;
else ([да])
:Найти карточку пациента в
картотеке;
endif

:Проверить график работы\nтребуемого врача;

if (Свободно ли назначенное время?) then ([врач свободен])
else if (Устраивает ли другое время?) then ([другое время])
else 
stop
endif
:Оформить талон
на приём; 
stop

@enduml