@startuml activity
title Диаграмма деятельностей сотрудника регистратуры 
start
if (Зарегисрирован ли пациент?) then ([нет])
fork
:Получить
паспорт;
fork again
:Получить
страховой полис;
end fork
:Открыть новую карточку;
:Ввести данные;
else ([да])
:Найти карточку пациента в
картотеке;
endif

if (Свобоно ли назначеное время?) then ([свободен])
else if (Устраивает ли другое время?) then ([другое время])
else 
stop
endif
:Оформить талон
на прием; 
stop

@enduml