@startuml class
left to right direction
skinparam class {
  BackgroundColor #7acff5
  Shadowing true
}

class Пациент {
- Номер карточки
- ФИО пациента
- Год рождения
- Адрес
- Пол
+ Зарегистрировать()
+ Обновить()
+ Удалить()
}

enum "Вид лечения" <<enumeration>>  {
- стационарно
- амбулаторно
}

class Лечение {
- ФИО пациента
- Описания лечения
- Вид лечения
+ Назначить()
+ Переопределить()
}


class Участок {
- Номер участка
- Адреса
}
Пациент "*" - "1" Участок

class Адреса {
- Район
- Улица
}
Участок "1" -- "*" Адреса

class "Прием пациентов" {
- Номер талона
- Время начала
- Дата открытия
- Дата приема
- Время окончания
- Анамнез
- Диагноз
+ Добавить()
}
Пациент "1" -- "1" "Прием пациентов"

Лечение -* "Прием пациентов" : Создает
"Вид лечения" -- Лечение

class Рецепты {
- Номер рецепта
- ФИО врача
- Название лекарства
- Количество
- Периодичность
+ Выписать()
}

class "Больничные листы" {
- Номер больничного листа
- Дата закрытия
+ Открыть()
+ Продлить()
+ Закрыть()
}

class Талоны {
- Номер талона
- ФИО врача
- ФИО пациента
- Дата
- Время
+ Выписать()
}

"Прием пациентов" o-- Рецепты
"Прием пациентов" o-- "Больничные листы"
"Прием пациентов" o-- Талоны

class Врач {
- Табельный номер
- ФИО врача
- Специализация
- Должность
- Отделение
- Категория
- Время четное
- Время нечетное
- Участок
- Тип врача
+ Добавить()
+ Удалить()
+ Обновить()
}

Участок "1" - "*" Врач

enum "Тип врача" <<enumeration>> {
- Медсестра
- Терапевт
- Дежурный врач
- Врач специализации
}

Врач -- "Тип врача" 

class "График дежурств" {
- ФИО врача
- Дата
- Месяц
}

Врач "1" -- "1..2" "График дежурств"

class Кабинет {
- Номер кабинета
- Телефон
- Отделение
}
Врач "1..2" -- "1" Кабинет

class Отделение {
- Название
- Специализация
- ФИО завотделения
- Этаж
+ Обновить()
}
Врач "*" -- "1" Отделение
Отделение "2..8" - "1" Кабинет

class Услуги {
# Название услуги
+ Добавить()
+ Удалить()
+ Редактировать()
}

Отделение "1" -- "*" Услуги

class "Платные услуги" {
- Стоимость
}
Услуги <|- "Платные услуги"

hide circle
@enduml