@startuml sequence
title Фрагмент диаграммы последовательностей
hide footbox
skinparam actor {
    BackgroundColor #7acff5
}
skinparam participant {
    BackgroundColor #7acff5
}

actor Пациент
actor "Сотрудник регистратуры"
participant ":карточки пациентов"
participant ":прием"
actor Врач
activate Пациент #7acff5
activate "Сотрудник регистратуры" #7acff5
activate Врач #7acff5
autonumber 1
Пациент -> "Сотрудник регистратуры": Обращение в регистратуру
Пациент -> "Сотрудник регистратуры": Запрос на талон
Пациент <- "Сотрудник регистратуры": Талон на прием
autonumber 4.1
"Сотрудник регистратуры" -> ":карточки пациентов": Запрос на наличие
activate ":карточки пациентов" #7acff5
"Сотрудник регистратуры" -> ":карточки пациентов": карточка
deactivate ":карточки пациентов"
autonumber 5
Пациент -> "Сотрудник регистратуры": Запрос на карточку 
Пациент <- "Сотрудник регистратуры": Карточка клиента
":прием" <- Врач: Запись в карточку
activate ":прием" #7acff5
Пациент -> ":прием": Жалобы
deactivate ":прием"



@enduml