@startuml
title Фрагмент диаграммы последовательностей
hide footbox
skinparam actor {
    BackgroundColor #7acff5
}
skinparam participant {
    BackgroundColor #7acff5
}

actor Пациент
actor "Сотрудник регистратуры"
participant ":карточки пациентов"
participant ":прием"
actor Врач
activate Пациент #7acff5
activate "Сотрудник регистратуры" #7acff5
activate Врач #7acff5
Пациент -> "Сотрудник регистратуры": 1: Обращение в регистратуру
Пациент -> "Сотрудник регистратуры": 2: Запрос на талон
Пациент <- "Сотрудник регистратуры": 3: Талон на прием
"Сотрудник регистратуры" -> ":карточки пациентов": 4: Запрос на наличие
activate ":карточки пациентов" #7acff5
"Сотрудник регистратуры" -> ":карточки пациентов": 4.1: карточка
deactivate ":карточки пациентов"
Пациент -> "Сотрудник регистратуры": 5: Запрос на карточку 
Пациент <- "Сотрудник регистратуры": 6: Карточка клиента
":прием" <- Врач: 7: Запись в карточку
activate ":прием" #7acff5
Пациент -> ":прием": 8: Жалобы
deactivate ":прием"



@enduml